name: V2Ray Config Extractor

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    # این بخش جدید، دسترسی لازم برای نوشتن در ریپازیتوری را می‌دهد
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python main.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          CHANNEL_USERNAMES: ${{ secrets.CHANNEL_USERNAMES }}

      - name: Commit and push if changed
        run: |
          if [ -f subscription.txt ]; then
            echo "✅ Subscription file found. Committing changes..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add subscription.txt
            git diff --staged --quiet || git commit -m "Update subscription file"
            git push
          else
            echo "⚠️ Subscription file not found. No new working configs were found in this run."
          fi